#name: 更新文件索引
#on:
#  push:
#    branches: [ main ]
#    paths:
#      - '**'                  # 监控所有文件变动
#      - '!.github/workflows/**' # 排除自身触发循环
#
#jobs:
#  update-index:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      
#      - name: 生成文件列表
#        run: |
#          # 排除特定文件
#          EXCLUDE=(".git" ".github" "README.md" "LICENSE" ".gitignore" "file-list.json")
#          
#          # 生成JSON格式索引
#          echo '[' > file-list.json
#          find . -type f \( ! -path "./.git/*" ! -name "file-list.json" \) \
#            -printf '  {"name": "%f", "size": %s, "path": "%p"},\n' \
#            | grep -vF "${EXCLUDE[@]/#/-e }" >> file-list.json
#          sed -i '$ s/,$//' file-list.json
#          echo ']' >> file-list.json
#          
#          # 验证生成结果
#          cat file-list.json
#          jq empty file-list.json # 验证JSON格式
#
#      - name: 提交变更
#        if: github.ref == 'refs/heads/main'
#        run: |
#          git config user.name "GitHub Actions"
#          git config user.email "actions@github.com"
#          git add file-list.json
#          git diff --cached --quiet || git commit -m "自动更新文件索引 [skip ci]"
#          git push
name: 生成文件列表
on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.github/**'

jobs:
  generate-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 生成索引
        run: |
          # 生成规范化的文件列表
          echo '[' > file-list.json
          find . -type f \
            -not -path "./.git/*" \
            -not -name "file-list.json" \
            -not -name "README.md" \
            -not -name "LICENSE" \
            -not -name ".gitignore" \
            -printf '  {"name":"%f","size":%s,"url":"https://bgithub.xyz/wujianson/dir/raw/main/%P"},\n' >> file-list.json
          sed -i '$ s/,$//' file-list.json
          echo ']' >> file-list.json
          
          # 验证格式
          jq empty file-list.json || exit 1
          echo "生成成功！文件数: $(jq length file-list.json)"

      - name: 提交变更
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "自动更新文件列表"
          file_pattern: file-list.json
